name: Daily Invite Script (Manual & Scheduled)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger (optional)'
        required: false
        default: 'Manual run'

  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点（北京时间8点）执行一次

jobs:
  run_invite_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run invite script
      id: run_script
      run: |
        python invite_script.py
